name: AnarchySpawn
version: @version@-@apiversion@
authors: [ DartPower, crazicrafter1 ]
website: https://github.com/dptmc/DPT-PluginRepoTemplate
main: io.dpteam.AnarchySpawn.Main
api-version: 1.13
commands:
  as:
    usage: /<command> [reload]
    description: reload config of AnarchySpawn
    permission: as.reload
permissions:
  as.reload:
    default: op